title: Fluorescence image analysis course - GloBIAS and CNR Naples - 2025
description: Introductory Course on BioImage Analysis for Microscopy - GloBIAS and CNR Naples 2025
show_downloads: true
google_analytics:
theme: jekyll-theme-slate
