title: Introductory Course on BioImage Analysis for Microscopy  GloBIAS CNR Naples_2025
description: BIA for microscopy course GloBIAS CNR Naples 2025
show_downloads: true
google_analytics:
theme: jekyll-theme-slate
